# Use a lightweight Python base image
FROM python:3.10-slim-buster
SHELL ["/bin/bash", "-c"]

# Set the working directory in the container
WORKDIR /app

# Copy the environment.yml file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Expose the port the app runs on
EXPOSE 8001

# Command to run the application
CMD ["uvicorn", "rate_limiting_service:app", "--host", "0.0.0.0", "--port", "8001"]